apply plugin: 'com.android.library'

android {
    compileSdk = 36

    defaultConfig {
        minSdkVersion 18
        targetSdkVersion 36
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'jp.kshoji.blemidi.unityplayermock'
}
