apply plugin: 'com.android.application'

android {
    compileSdk = 36

    defaultConfig {
        applicationId "jp.kshoji.blemidi.sample"
        minSdkVersion 18
        targetSdkVersion 36
        versionCode 3
        versionName "1.2"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'jp.kshoji.blemidi.sample'
}

repositories {
    maven {
        url 'https://github.com/kshoji/javax.sound.midi-for-Android/raw/master/javax.sound.midi/repository'
    }
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':BLE-MIDI-library')
    api 'androidx.annotation:annotation:1.9.1'
}
